2018-03-11 04:05:19 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=20 from 2018-03-11 03:59:06.005052)
2018-03-11 04:05:23 WARNING (MainThread) [custom_components.sensor.heatpump_temp] hp name: climate.1st_fl_heatpump, state: None
2018-03-11 04:05:24 ERROR (MainThread) [homeassistant.components.sensor] Error on device update!
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_component.py", line 217, in async_add_entity
    yield from entity.async_device_update(warning=False)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 304, in async_device_update
    yield from self.async_update()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/home/homeassistant/.homeassistant/custom_components/sensor/heatpump_temp.py", line 75, in async_update
    self._state = heatpump_states.attributes.get('current_temperature')
AttributeError: 'NoneType' object has no attribute 'attributes'
2018-03-11 04:05:43 WARNING (Thread-4) [netdisco.ssdp] Error fetching description at http://192.168.1.1:1990/WFADevice.xml
2018-03-11 04:05:44 WARNING (Thread-4) [netdisco.ssdp] Error fetching description at http://192.168.1.254:1990/WFADevice.xml
2018-03-11 04:06:01 WARNING (MainThread) [homeassistant.components.media_player] Setup of platform cast is taking over 10 seconds.
2018-03-11 04:06:01 WARNING (MainThread) [homeassistant.components.media_player] Setup of platform cast is taking over 10 seconds.
2018-03-11 04:06:01 WARNING (MainThread) [homeassistant.components.media_player] Setup of platform cast is taking over 10 seconds.
2018-03-11 04:06:02 WARNING (MainThread) [homeassistant.components.media_player] Setup of platform cast is taking over 10 seconds.
2018-03-11 04:06:02 WARNING (MainThread) [homeassistant.components.media_player] Setup of platform cast is taking over 10 seconds.
2018-03-11 04:06:02 WARNING (MainThread) [homeassistant.components.media_player] Setup of platform cast is taking over 10 seconds.
2018-03-11 04:36:44 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal read error on socket transport
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
OSError: [Errno 113] No route to host
2018-03-11 04:36:48 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal read error on socket transport
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
OSError: [Errno 113] No route to host
2018-03-11 08:01:14 ERROR (zeroconf-ServiceBrowser__miio._udp.local.) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/climate/mitsubishi_mqtt.py", line 102, in message_received
    self.schedule_update_ha_state()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 273, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'
2018-03-11 08:39:17 WARNING (Thread-46) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 08:39:17 WARNING (Thread-44) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 08:39:17 WARNING (Thread-43) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 08:39:17 WARNING (Thread-42) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 08:39:17 WARNING (Thread-45) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 08:39:17 WARNING (Thread-41) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 08:39:25 ERROR (Thread-41) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 08:39:25 ERROR (Thread-45) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 08:39:25 ERROR (Thread-44) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 08:39:25 ERROR (Thread-43) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 08:39:25 ERROR (Thread-46) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 08:39:25 ERROR (Thread-42) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 08:45:09 WARNING (Thread-50) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 08:45:09 WARNING (Thread-47) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 08:45:10 WARNING (Thread-48) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 08:45:10 WARNING (Thread-52) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 08:45:10 WARNING (Thread-49) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 08:45:11 WARNING (Thread-51) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 08:45:17 ERROR (Thread-47) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 08:45:17 ERROR (Thread-50) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 08:45:17 ERROR (Thread-52) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 08:45:17 ERROR (Thread-48) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 08:45:17 ERROR (Thread-49) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 08:45:18 ERROR (Thread-51) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 08:48:06 WARNING (Thread-28) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 08:48:06 WARNING (Thread-26) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 08:48:15 WARNING (Thread-23) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 08:48:15 WARNING (Thread-25) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 08:48:15 WARNING (Thread-24) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 08:48:15 WARNING (Thread-27) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 08:48:18 ERROR (Thread-23) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 08:48:18 ERROR (Thread-27) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 08:48:18 ERROR (Thread-24) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 08:48:18 ERROR (Thread-25) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 08:48:21 ERROR (Thread-28) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 08:48:21 ERROR (Thread-26) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 09:30:21 WARNING (Thread-37) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 09:30:21 WARNING (Thread-36) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 09:30:21 WARNING (Thread-38) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 09:30:21 WARNING (Thread-39) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 09:30:21 WARNING (Thread-35) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 09:30:21 WARNING (Thread-40) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-03-11 09:30:37 ERROR (Thread-39) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 09:30:37 ERROR (Thread-37) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 09:30:37 ERROR (Thread-35) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 09:30:37 ERROR (Thread-40) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 09:30:37 ERROR (Thread-38) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-03-11 09:30:37 ERROR (Thread-36) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
